#!/usr/bin/env bash
# Build an AgentVM image with the pi coding agent preinstalled.
#
# Requires image/preinstalled/usrlocal, generated by image/preinstall-pi.sh.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-$HERE/agentvm-alpine-python-node-pi.wasm}"

export DOCKERFILE=Dockerfile.pi
export IMAGE_NAME=agentvm-alpine-python-node-pi:riscv64

exec "$HERE/build.sh" "$OUT"
